name: protractor-es6modules-typescript-tsnode-jasmine

on: 
  push:
  schedule:
    - cron: '0 0 2-30/2 * *'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: INSTALL, UPDATE_WEBDRIVER
      run: |
        npm ci
        npm run upadte-webderiver
      env:
        CI: true
    - name: TEST
      run: |
        npm run test-ci
