name: protractor-typescript-ts-node-jasmine-expect
'on':
  push: null
  schedule:
    - cron: 20 2 1-31/2 * *
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: NPM_INSTALL
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm install
        env:
          CI: true
      - name: LINT
        run: npm run lint --if-present
      - name: BUILD
        run: npm run build --if-present
      - name: UPDATING_WEBDRIVER
        run: 'npm run update:webdriver'
      - name: EXECUTING_TESTS
        run: npm run test
